force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <displayFormat>ORD-{0000}</displayFormat>
        <label>Custom Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Custom Orders</relationshipLabel>
    <relationshipName>Custom_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Draft</fullName>
                <default>true</default>
                <label>Not Draft</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomOrderCleanerTest.cls
@isTest
private class CustomOrderCleanerTest {

    @TestSetup
    static void testSetup(){

        List<Contact> contacts = new List<Contact> {
            new Contact (FirstName = 'firstname', LastName = 'lastname'),
            new Contact (FirstName = 'lastname', LastName = 'firstname')
        };

        insert contacts;
        List<Custom_Order__c> cOrders = new List<Custom_Order__c>();

        for (Contact contact : contacts) {
            cOrders.add(new Custom_Order__c(Contact__c = contact.Id, Status__c = 'Draft'));
            cOrders.add(new Custom_Order__c(Contact__c = contact.Id, Status__c = 'Draft'));
            cOrders.add(new Custom_Order__c(Contact__c = contact.Id, Status__c = 'Not Draft'));
            cOrders.add(new Custom_Order__c(Contact__c = contact.Id, Status__c = 'Not Draft'));
        }

        insert cOrders;
    }

    @isTest
    private static void testCustomOrderCleaner() {
        String sch = '0 0 0 15 3 ? 2022';
        CustomOrderCleaner cleaner = new CustomOrderCleaner();

        Test.startTest();
        System.schedule('Deleting Draft Status Orders', sch, cleaner);
        System.assertEquals(8, [SELECT COUNT() FROM Custom_Order__c]);
        Test.stopTest();

        System.assertEquals(0, [SELECT COUNT() FROM Custom_Order__c WHERE Status__c = 'Draft']);
        System.assertEquals(4, [SELECT COUNT() FROM Custom_Order__c]);
    }

}