force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <displayFormat>ORD-{0000}</displayFormat>
        <label>Custom Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Custom Orders</relationshipLabel>
    <relationshipName>Custom_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Draft</fullName>
                <default>true</default>
                <label>Not Draft</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduledJob.cls
global class ScheduledJob implements Schedulable {

    global void execute(SchedulableContext ctx) {
        List<Contact> contacts = [
            SELECT Id, Name
            FROM Contact
        ];
        createOrders(contacts);
    }

    public void createOrders(List<Contact> contacts) {
        List<Custom_Order__c> orders = new List<Custom_Order__c>();

        for (Contact contact : contacts) {
            orders.addAll(new List<Custom_Order__C> {
                new Custom_Order__c(Status__c = 'Draft', Contact__c = contact.Id),
                new Custom_Order__c(Status__c = 'Draft', Contact__c = contact.Id),
                new Custom_Order__c(Status__c = 'Draft', Contact__c = contact.Id),
                new Custom_Order__c(Status__c = 'Draft', Contact__c = contact.Id),
                new Custom_Order__c(Status__c = 'Draft', Contact__c = contact.Id),
                new Custom_Order__c(Status__c = 'Draft', Contact__c = contact.Id),
                new Custom_Order__c(Status__c = 'Draft', Contact__c = contact.Id),
                new Custom_Order__c(Status__c = 'Draft', Contact__c = contact.Id),
                new Custom_Order__c(Status__c = 'Draft', Contact__c = contact.Id),
                new Custom_Order__c(Status__c = 'Draft', Contact__c = contact.Id)
            });
        }

        insert orders;
    }
}